/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestFontsRouteImport } from './routes/test-fonts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FontsSlugRouteImport } from './routes/fonts.$slug'
import { Route as ApiRevalidateRouteImport } from './routes/api.revalidate'

const TestFontsRoute = TestFontsRouteImport.update({
  id: '/test-fonts',
  path: '/test-fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsSlugRoute = FontsSlugRouteImport.update({
  id: '/fonts/$slug',
  path: '/fonts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-fonts': typeof TestFontsRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/fonts/$slug': typeof FontsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-fonts': typeof TestFontsRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/fonts/$slug': typeof FontsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-fonts': typeof TestFontsRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/fonts/$slug': typeof FontsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-fonts' | '/api/revalidate' | '/fonts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-fonts' | '/api/revalidate' | '/fonts/$slug'
  id: '__root__' | '/' | '/test-fonts' | '/api/revalidate' | '/fonts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestFontsRoute: typeof TestFontsRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  FontsSlugRoute: typeof FontsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-fonts': {
      id: '/test-fonts'
      path: '/test-fonts'
      fullPath: '/test-fonts'
      preLoaderRoute: typeof TestFontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts/$slug': {
      id: '/fonts/$slug'
      path: '/fonts/$slug'
      fullPath: '/fonts/$slug'
      preLoaderRoute: typeof FontsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestFontsRoute: TestFontsRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  FontsSlugRoute: FontsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
